### ISSUE TITLE
TBD: clean up code from tidy-messages 

### ISSUE THREAD

**Issue by imahjoub** [imahjoub/pi_spigot#10]

**Comment by imahjoub** [comment]
Hi @ckormanyos,

the pi_spigot project is now partially clean from tidy warnings, but there are few warnings that I've disabled.

If you have some time this week or next week, we can review them together. I would like to hear your opinion on this.

Thanks and kind regards, Iliass

**Comment by ckormanyos** [comment]
Hi @imahjoub it looks good to me.

As for the tidy syntax, it is looking clean to me.

A few other things that caught my attention...

Now that you've gone "header-only" on the implementation, I was considering you might want to move the detailed comments regarding performance out of the header file and into the test file. This would keep the header more clean.

Also I think the large tabulated control value of pi could go constexpr with some modifications. I pülayed around with this but have noy yet gotten the implementatoin right. i'll let you know if/when I do.

**Comment by imahjoub** [comment]
Hi @ckormanyos,

thank you so much, I have reviewed your changes. Now the header file looks very simple and clear.

**Comment by ckormanyos** [comment]
> the header file looks very simple and clear

Thanks @imahjoub it is a nice project.
