### ISSUE TITLE
universal driver or application to edit changes the values of rad E PI and Tau

### ISSUE THREAD

**Issue by KonstaMF** [imahjoub/pi_spigot#19]
Hello, I need your help, I need a universal driver or application to edit changes the values of rad E PI and Tau in Math.NET to run the System and applications, I need it for scientific experiment in the field of transformations in calculations and generation, I hope for your help. Regards.

**Comment by imahjoub** [comment]
Hello @KonstaMF,

what do you mean with **"a universal driver or application to edit changes the values of rad E PI and Tau"**?

Do you need high precision values of Pi and Tau ? 

Regards

**Comment by KonstaMF** [comment]
Hello, I wrote down the very idea that I would like to introduce to you, I need help in implementing it.
https://github.com/KonstaMF/Math-Driver-Extend
